using System;
using System.Linq;
using System.ServiceModel;

namespace WcfSelfHostedServer
{
	class Program
	{
		static void Main(string[] args)
		{
			// the cert was generated by running following at a vs developer command prompt (so that the programs are in path)
			// makecert -n CN=identityfail.local -pe -$ commercial -a sha256 -sky exchange -sv IdentityFail.pvk IdentityFail.cer
			// pvk2pfx - pvk IdentityFail.pvk - pi IdentityFail - spc IdentityFail.cer - pfx IdentityFail.pfx - f
			//
			// IdentityFail.pfx should be installed in LocalComputer Personal store

			var host = new ServiceHost(typeof(Service), new[] { new Uri(string.Format("net.tcp://localhost:30000/Service.svc", Environment.MachineName)) });
			host.Open();
			Console.WriteLine("Hosting at {0}", host.ChannelDispatchers.Single().Listener.Uri.AbsoluteUri);

			Console.ReadLine();
		}
	}
}
